export type VideoArchive = {
  id: string;
  saison: string;
  titre: string;
  description: string;
  thumbnail: string;
  videos: { label: string; id: string }[];
};

export const VIDEOS_ARCHIVES: VideoArchive[] = [
  {
    id: "auditions-2010",
    saison: "2010–2011",
    titre: "Auditions de décembre 2010",
    description: "Extraits de Racine et Hugo — groupe adultes du lundi 20h",
    thumbnail: "Ayn8svQbbeU",
    videos: [
      { label: "Diaporama lundi (1)", id: "Ayn8svQbbeU" },
      { label: "Diaporama lundi (2)", id: "rN4V2gjkiIo" },
      { label: "Diaporama mardi & mercredi", id: "GIx4oI9AOCY" },
      { label: "Phèdre — J. Sabourault", id: "AzPZay3-duM" },
      { label: "Andromaque — B. Gervais", id: "qQWxmUXI5J8" },
      { label: "Andromaque — J. Le Roy", id: "jdNGN7_6MYA" },
      { label: "Andromaque — F. Murphy", id: "-qblxzz6HtE" },
      { label: "Andromaque — E. Delacour", id: "BpL6LxBJi6I" },
      { label: "Andromaque — A. Prouvost", id: "pQjJUNaLFME" },
      { label: "Iphigénie — S. Bernier", id: "nvKn8nmldJQ" },
      { label: "Iphigénie — C. Chassaigne-Rouzet", id: "bILm_VcqfD4" },
      { label: "Iphigénie — C. Péchiney", id: "piSA7h4gdiM" },
      { label: "Mithridate — E. Hirsch-Sene", id: "3axv4KpxjYQ" },
      { label: "Hernani — M. Berra", id: "L9iRIY6SWhI" },
      { label: "Mot final — H. Toutain", id: "dPEFjimyMEk" },
    ],
  },
  {
    id: "barbe-bleue-oct-2010",
    saison: "Octobre 2010",
    titre: "Au Doux Pays de Barbe Bleue",
    description: "Texte et mise en scène d'Hélène Toutain",
    thumbnail: "CkdhOum7mpU",
    videos: [{ label: "Diaporama", id: "CkdhOum7mpU" }],
  },
  {
    id: "entre-hier-demain",
    saison: "Janvier 2010",
    titre: "Entre hier et demain",
    description: "Texte et mise en scène d'Hélène Toutain — groupe adultes",
    thumbnail: "80nsaTxL8AA",
    videos: [{ label: "Extrait", id: "80nsaTxL8AA" }],
  },
  {
    id: "arlequin",
    saison: "2009–2010",
    titre: "Une aventure d'Arlequin",
    description: "Représentations de fin d'année",
    thumbnail: "9X1mZiwk6oI",
    videos: [
      { label: "Partie 1", id: "9X1mZiwk6oI" },
      { label: "Partie 2", id: "JrRDw3Gb4F8" },
      { label: "Partie 3", id: "BsEM5axJxTU" },
      { label: "Partie 4", id: "659UNFtPsck" },
      { label: "Diaporama", id: "CxvtD12BoeE" },
    ],
  },
  {
    id: "precieuses-ridicules",
    saison: "2009–2010",
    titre: "Les Précieuses Ridicules",
    description: "Représentations de fin d'année",
    thumbnail: "7Uh4EJyPSEw",
    videos: [
      { label: "Partie 1", id: "7Uh4EJyPSEw" },
      { label: "Partie 2", id: "P8c1JLBB01A" },
      { label: "Partie 3", id: "3g5nA8Dtxfs" },
      { label: "Diaporama", id: "-1L3R-V0ZsQ" },
    ],
  },
  {
    id: "marmite",
    saison: "2009–2010",
    titre: "La Marmite",
    description: "Représentations de fin d'année",
    thumbnail: "cGGi8ha8AdE",
    videos: [
      { label: "Partie 1", id: "cGGi8ha8AdE" },
      { label: "Partie 2", id: "wBk7Pz3Oo20" },
      { label: "Partie 3", id: "0r26_pZGiwU" },
      { label: "Partie 4", id: "XmEn96jQZxA" },
    ],
  },
  {
    id: "barbe-bleue",
    saison: "2009–2010",
    titre: "Barbe Bleue",
    description: "Représentations de fin d'année",
    thumbnail: "Gb915lbgWB8",
    videos: [
      { label: "Partie 1", id: "Gb915lbgWB8" },
      { label: "Partie 2", id: "p2WneHQGR6k" },
      { label: "Partie 3", id: "qh2oB4emhjM" },
      { label: "Partie 4", id: "Hyiqa6ZcyDM" },
      { label: "Partie 5", id: "hm246x7LDLY" },
      { label: "Partie 6", id: "WKd9cdxklLU" },
    ],
  },
  {
    id: "truands",
    saison: "2009–2010",
    titre: "Les Truands",
    description: "Représentations de fin d'année",
    thumbnail: "onzFfol_avw",
    videos: [
      { label: "Partie 1", id: "onzFfol_avw" },
      { label: "Partie 2", id: "3979xq4k-c4" },
      { label: "Partie 3", id: "hPhyLJmVMv8" },
      { label: "Partie 4", id: "9BenqOGbgyE" },
      { label: "Partie 5", id: "lB0nPqNP4kQ" },
      { label: "Partie 6", id: "fCAJnkdDk8E" },
      { label: "Partie 7", id: "FxiR3iQiNfU" },
      { label: "Partie 8", id: "1tiO3F0TUOo" },
    ],
  },
  {
    id: "doux-pays",
    saison: "2009–2010",
    titre: "Au Doux Pays de Barbe Bleue",
    description: "Représentations de fin d'année",
    thumbnail: "ZmVpirq1QcE",
    videos: [
      { label: "Partie 1", id: "ZmVpirq1QcE" },
      { label: "Partie 2", id: "RNDP5_Wwirw" },
      { label: "Partie 3", id: "D_YUMIn3F6A" },
      { label: "Partie 4", id: "bsCdIXwuBqA" },
      { label: "Partie 5", id: "3wRc45dPy3k" },
      { label: "Partie 6", id: "hcEVfqO6SxM" },
      { label: "Partie 7", id: "BUqSvr0lO4c" },
      { label: "Partie 8", id: "2_qc65oEA4Q" },
      { label: "Partie 9", id: "GjMg4R5_nyY" },
      { label: "Diaporama", id: "HZ7-rzoOHe4" },
    ],
  },
];
